---
namespace: ginigangadharan
name: custom_modules
version: 1.0.11
readme: README.md
authors:
  - Gineesh Madapparambath <net.gini@gmail.com>
description: Ansible Custom Module Demos
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - demos
  - ansible
  - devops
dependencies: {}
repository: https://github.com/ginigangadharan/ansible-collection-custom-modules
documentation: https://github.com/ginigangadharan/ansible-collection-custom-modules
homepage: https://github.com/ginigangadharan/ansible-collection-custom-modules
issues: https://github.com/ginigangadharan/ansible-collection-custom-modules/issues

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
